main: com.frinto.friends.Main
version: 1.0
name: frinto_friends
author: Frinto

commands:
  friends:
      description: Friends.
  fadd:
        description: Friends.
        usage: usage /fadd <player>
  fremove:
        description: Friends.
        usage: usage /fremove <player>
  flist:
        description: Friends.
        usage: usage /flist