main: com.frinto.friends.Main
version: 1.0
name: frinto_friends
author: Frinto

commands:
  friends:
        description: Friends.
  fadd:
        description: Friends.

  fremove:
        description: Friends.

  flist:
        description: Friends.
        